language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://alombardi.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "IFQtuSXzQ0nc3/XXcSqICxOG4jIXVqcbyExx9moeKdWh1B1sf8vFPm+N7s12RAhj0L4us+o+cWoy2gzTmXMT4Da6IO9/v9VKYCRMPgnfStwMxll/sPoPqFU7SuNM10wDqZ5kDjBjXLLKTXvFfhvxoczsZB3NETYWZpw8WD3hXVhTO8hpjyIZXFR9tAVno3tGliN/GchepyDcDlL010yWnyWIePCcLZTYS9RH7z0kEHNgnt+7ck5ezskfPHn2SKkAtuduSPvnDknQLw0735BHo7HuqYi1oPhVV1cur/NMx/miPOGO+s5GL/9HsT9/hES7TnvmXogL41M6QQeFwxZUYgE40s7iYoVbkCpwcba6PL1AcPkpa0WBc5gPc/9ecSOZJewItV/WULGkYV2IAyNI6CXt1M/L8CcIjSoDB4UPGeHsQRWTkSOuE6OmEYRznK31HtmAQjp5sQi4do1u04l4RPRgCS9l/W7qAF7lMzRKCv8lknorVGNxgjYm3v+GrTKa9bgoCoVQu9E+y5O0w21MdHDGgQq17mfs2391+ndcU/udCOgnGYPyK5fvSoY2bvivv9Hr8knKGNMr6DH/gXjB88hGbHXgpmz5z+Z/2Iue4bNa3WqxQP3VzvkFI1ZSrUeAV0qoBR1sHRz5hksgwdHc9qQ5TwCqVE6ZMQ2eQtHwOHk="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
